### PR TITLE
Add ability to export submissions

### PR DESCRIPTION
**Pull request by minhducsun2002**

### CODE REVIEW

**Comment by dungwinux** [comment]
What's happened with index.js ?

**Comment by dungwinux** [comment]
Please convert the source code from LF to CRLF

**Comment by minhducsun2002** [comment]
Forgot to run `eslint`. I'll get this done.

_Little recommendation : use `husky` like I did - you no longer have to remember linting._

**Comment by minhducsun2002** [comment]
Done.

**Comment by dungwinux** [comment]
refactor please.
And index.js still got whole file change

**Comment by minhducsun2002** [comment]
About `index.js` being changed as a whole, well, I don't know any better explanation than the line numbers changed.

About re-factoring... well, okay.

**Comment by minhducsun2002** [comment]
Wait, is there anything to be re-factored? If it is about linting, then :
```
$ git show HEAD
commit bb0484f9961edadeab4f96ac5f3011dd54177f56 (HEAD -> export)
Author: Minh Duc Vo <minhducsun2002@gmail.com>
Date:   Thu Apr 25 13:38:08 2019 +0700

    Edit the help statement a little

<...some diff>
$ git status src/extensions 
On branch export
nothing to commit, working tree clean
$ npx eslint --fix src/extensions/ 
$ git status src/extensions 
On branch export
nothing to commit, working tree clean
```

**Comment by dungwinux** [comment]
Let me check for functionalities, since it might conflict with `db.js` due to targeting same file. It would be better if it use function from `db.js` instead of creating seperate module

**Comment by minhducsun2002** [comment]
This implementation is now considered unmaintained. Closing PR.

**Pull request closed without merging**
