### PR TITLE
Allow administrators to change password of all users

### PR DESCRIPTION
**Pull request by minhducsun2002**
This should allow changing passwords of users whose have forgotten without restarting the whole server.

### CODE REVIEW

**Comment by minhducsun2002** [comment]
The first condition checks if the user is him/herself, and if (s)he is, then the whole expression is `false`, no error introduced.

**Comment by minhducsun2002** [comment]
I already considered that scenario and came to the conclusion that no further checks for it will be added. A rogue administrator can exist only through intervention from another administrator/the server operator themselves and thus, it cannot be prevented by technical methods.

**Comment by dungwinux** [comment]
@minhducsun2002, anything could happen. It is better to find way to reset the password.

**Comment by minhducsun2002** [comment]
Okay, I'mma ban administrators from attempting to mess up with other ones.

**Comment by dungwinux** [comment]
I just changed my mind

**Pull request closed without merging**
