### PR TITLE
Adding cross-origin support for API routes

### PR DESCRIPTION
**Pull request by minhducsun2002**
(About 458a3ed3e1cd164956d9a85732fcf5d2186f9e51 : Don't ask me why I don't `app.all` directly; it won't work, I tried).

### CODE REVIEW

**Comment by minhducsun2002** [comment]
About [this failed build](https://ci.appveyor.com/project/dungwinux/wafter/builds/23987155), be sure to load all submodules.

**Comment by dungwinux** [comment]
This would be good, but unfortunately, Wafter current possible authentication method is based on session cookies, which significantly defer the cors. The cors need to be limited further.

**Comment by minhducsun2002** [comment]
Hold on...what? May I request a clarification?

**Comment by minhducsun2002** [comment]
Closing this. It poses a security risk that I couldn't see earlier.

**Pull request closed without merging**
