### PR TITLE
Writing static version from package descriptor

### LINKED ISSUE #60: Apply version and config in bundle
### Issue
- The version on release doesn't match with the version in package.json and the version shown in menu.
- The config was not included in bundle, thus open to user

### PR DESCRIPTION
**Pull request by minhducsun2002**
Closes #60.

### CODE REVIEW

**Comment by minhducsun2002** [comment]
@dungwinux, can you drop `envify` from `package.json`? It is not needed - I could not find a way to use it properly.

**Comment by dungwinux** [comment]
What `envify` ? It's not there from beginning

**Comment by minhducsun2002** [comment]
I removed them? Oh well, nevermind, carry on with any test you might be doing.

**Comment by dungwinux** [comment]
Rejected due to using `process.env.npm_package_version`

**Pull request closed without merging**
